USE COMPANY;
GO;

ALTER TABLE EMPLOYEE
    ADD PRIMARY KEY (Ssn);
ALTER TABLE DEPARTMENT
    ADD PRIMARY KEY (Dnumber);

ALTER TABLE EMPLOYEE
    ADD FOREIGN KEY (Dno) REFERENCES DEPARTMENT(DNumber);
ALTER TABLE DEPARTMENT
    ADD FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn);

GO;